"""Curated skill/technology tokens for extraction and JD matching."""

SKILL_CATALOG: frozenset[str] = frozenset(
    {
        "python",
        "javascript",
        "typescript",
        "java",
        "c++",
        "c#",
        "go",
        "golang",
        "rust",
        "ruby",
        "php",
        "swift",
        "kotlin",
        "scala",
        "r",
        "sql",
        "html",
        "css",
        "react",
        "next.js",
        "nextjs",
        "vue",
        "angular",
        "svelte",
        "node.js",
        "nodejs",
        "express",
        "fastapi",
        "django",
        "flask",
        "spring",
        "spring boot",
        ".net",
        "graphql",
        "rest",
        "api",
        "microservices",
        "docker",
        "kubernetes",
        "aws",
        "azure",
        "gcp",
        "terraform",
        "ci/cd",
        "github actions",
        "jenkins",
        "linux",
        "git",
        "postgresql",
        "postgres",
        "mysql",
        "mongodb",
        "redis",
        "elasticsearch",
        "kafka",
        "rabbitmq",
        "pandas",
        "numpy",
        "scikit-learn",
        "sklearn",
        "tensorflow",
        "pytorch",
        "machine learning",
        "deep learning",
        "nlp",
        "computer vision",
        "data analysis",
        "data engineering",
        "etl",
        "spark",
        "hadoop",
        "tableau",
        "power bi",
        "excel",
        "agile",
        "scrum",
        "jira",
        "figma",
        "ui/ux",
        "tailwind",
        "sass",
        "webpack",
        "vite",
        "jest",
        "pytest",
        "cypress",
        "selenium",
        "oauth",
        "jwt",
        "security",
        "encryption",
        "blockchain",
        "solidity",
        "flutter",
        "react native",
        "ios",
        "android",
        "devops",
        "monitoring",
        "prometheus",
        "grafana",
        "llm",
        "openai",
        "langchain",
        "vector database",
        "pinecone",
        "communication",
        "leadership",
        "problem solving",
        "teamwork",
        "project management",
    }
)
